### PR TITLE
Create rise-distribution component

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep Were you intending to leave out the `circle.yml` file?

**Comment by donnapep** [comment]
@stulees There are no tests for this component since it doesn't have any functionality, so I don't really see a need for a `circle.yml`.

**Comment by stulees** [comment]
@donnapep Okay :+1:

**Pull request merged**
